### ISSUE TITLE
uploading teacher tips via administration not working

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#160]
I am trying to update/delete/add a Teacher Tips document when logged in, using the administration tools. However, nothing seems to change when I update/delete/add a document. It might appear deleted when viewing the simulation info, but it does not get updated on the actual sim page. When I upload a file, then view the file within administration or from a sim page, it only shows the old one. 

To be clear, I am not viewing this on phet-dev, I'm trying to do this on the main site.

**Comment by aaronsamuel137** [comment]
It might be that the data was cached somewhere and there was a delay before it showed up on the sim page. Can you check the page now and see if it has been updated? If not, I will look into this some more. I would be surprised if this broke somehow on the main site when it used to be working since I haven't touched this code.

**Comment by amanda-phet** [comment]
I never checked that it worked before now, unfortunately, so I don't think it's related to any of the recent changes.

**Comment by arouinfar** [comment]
@aaronsamuel137, this issue still persists after the launch of new sim pages. I am unable to upload a teacher tips document to a HTML5 sim page. 

On the administration page for the sim, there is a field to upload the file. After selecting the file:
![image](https://cloud.githubusercontent.com/assets/8419308/7818545/ba9bfd5a-0399-11e5-90a9-c79878bb1104.png)

After clicking submit, the chosen file disappears and no changes appear to have been made:
![image](https://cloud.githubusercontent.com/assets/8419308/7818547/c2dc6e46-0399-11e5-9cd6-b0cdaaa71aef.png)

**Comment by aaronsamuel137** [comment]
Sorry about the delay in working on this. I'm guessing this should be fairly high priority with the new sim pages deployed. I'll start looking at it today.

**Comment by aaronsamuel137** [comment]
@arouinfar, after you press submit, are you redirected back to the admin page with all of the sims listed, or do you stay on the same page?

**Comment by aaronsamuel137** [comment]
I have attempted a fix for this that seems to work on the test cases I have tried so far. (I removed area builder guide and re-uploaded it).

Note: the expected behavior for adding/removing a guide is that you will be redirected back to the admin page with all of the simulations. If this does not happen, there was probably an error.

Even if there is a guide uploaded, you will see "No file chosen". This is because the file uploader itself has nothing selected to be uploaded - it doesn't mean there is no file on the server. You can tell if there is a file on the server because you will see the option to "open the current guide or remove the guide".

Sorry this functionality is a little clunky, but it should at least work. If not let me know exactly what you are trying and what happens.

Assigning to @arouinfar or @amanda-phet for review.

**Comment by arouinfar** [comment]
Thanks, @aaronsamuel137! It seems like everything is working now. Previously, I would remain on the same page after attempting to upload the file. I'm now successfully redirected to the main simulations page in the administration section. 

I've uploaded a teacher tips document for Energy Skate Park: Basics. I caught a broken link in the original document I uploaded, but was able to successfully replace the file with an updated version.  This issue appears to have been resolved, so I'll go ahead and close it.

**Comment by amanda-phet** [comment]
I am only noticing this now that we are uploading tips, but these seem to be visible only when logged in. Can you make the teacher tips always visible? Currently, only the primer video is hidden until logged in (and there is a note when applicable).

**Comment by amanda-phet** [comment]
I logged out and now I'm still seeing them. Do you know why I couldn't see them before? I refreshed a bunch of times and it was only after logging in that I saw @arouinfar 's ESPB tips. Now I am still seeing them all...

**Comment by amanda-phet** [comment]
Maybe it was a fluke?

**Comment by arouinfar** [comment]
Strange! After uploading the file, the teacher tips became immediately visible to me on the sim page. I used my personal laptop to check if the teacher tips for ESPB were visible without signing in, and I was still able to see the file.

**Comment by amanda-phet** [comment]
Maybe it was just a temporary glitch. I'll close the issue.
